//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteOnline.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRole
    {
        public int Id { get; set; }
        public Nullable<int> ID_Role { get; set; }
        public Nullable<int> MaKhachHang { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual Role Role { get; set; }
    }
}
